---
- name: Prompt for become password and store securely
  hosts: localhost
  strategy: linear
  gather_facts: false
  roles:
    - 1_pre
    - 2_peri
    - 3_post

 


      # run_once: true

# - name: Run Once Before PlayBooks
#   hosts: localhost#
#   become: true

#   vars:
#     playbook:
#     - aur_helper.yml
#     - package_install.yml
#     - gnome-extensions.yml

#   tasks:
#     - name: Include and run anothe playbook r {{ item }}
#       ansible.builtin.include_tasks: "/home/dameon/.local/share/chezmoi/Development/Arch-configuration/playbooks/post_arch-gnome_install/{{ item }}"
#       loop: "{{ playbook }}"
