---
- name: Prompt for become password and store securely
  hosts: localhost
  gather_facts: false
  become: true

  vars_prompt:
    - name: become_password
      prompt: "Enter the become password"
      private: true # Do not echo the input
      encrypt: "sha256_crypt" # Encrypting the password (optional, for demonstration)
      confirm: true # Ask for confirmation

  pre_tasks:
    - name: Store become password securely
      ansible.builtin.copy:
        content: "{{ become_password }}"
        dest: "{{ source_dir }}/Development/ansible/arch_config/roles/pre/vars/become_pass.yml"
        mode: '0600'
      delegate_to: localhost

  roles:
    - pre
    - peri
    - post
