---
# vars file for peri

peri_role: "peri"

directory: "{{ ansible_dir }}/roles/peri/tasks"

zsh_custom: "/usr/share/oh-my-zsh/custom/plugins"

zsh_addons:
  - repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "{{ zsh_custom }}/zsh-autosuggestions"
  - repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "{{ zsh_custom }}/zsh-syntax-highlighting"
  - repo: "https://github.com/zdharma-continuum/fast-syntax-highlighting.git"
    dest: "{{ zsh_custom }}/fast-syntax-highlighting"
  - repo: "https://github.com/marlonrichert/zsh-autocomplete.git"
    dest: "{{ zsh_custom }}/zsh-autocomplete"
    depth: 1

gnome_themes_and_icons:
      - "ocs://www.gnome-look.org/p/1961046/" # Gruvbox Plus Icon Pack
      - "ocs://www.opendesktop.org/p/1305251/" # Candy icons

files_to_copy:
  - src: "{{ ansible_dir }}/resources/files/.zprofile"
    dest: "{{ home_dir }}/.zprofile"

  - src: "{{ ansible_dir }}/resources/files/.zsh_history"
    dest: "{{ home_dir }}/.zsh_history"

  - src: "{{ ansible_dir }}/resources/files/.zshrc"
    dest: "{{ home_dir }}/.zshrc"

  - src: "{{ ansible_dir }}/resources/files/.zshrc.zni"
    dest: "{{ home_dir }}/.zshrc.zni"
  
  - src: "{{ ansible_dir }}/resources/files/.p10k.zsh"
    dest: "{{ home_dir }}/.p10k.zsh"
    
  - src: "{{ ansible_dir }}/resources/files/.my_aliasesced"
    dest: "{{ home_dir }}/.my_aliases"
  
  - src: "{{ansible_dir }}/resources/files/dconf_backups.tar.gz"
    dest: "/tmp/dconf_backups.tar.gz"

    
folders_to_copy:
  - src: "{{ ansible_dir }}/resources/files/kitty/"
    dest: "{{ home_dir }}/.config/kitty/"
  
  # - src: "{{ ansible_dir }}/resources/files/dconf_backup/"
  #   dest: "{{ home_dir }}.config/dconf_backup/"

  
  