---
- name: Gather Resources
  block:
    - name: Gather files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0700"
      loop: "{{ setup_gather_files }}"

    - name: Gather directory
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ setup_user_name }}"
        group: "{{ setup_user_name }}"
        mode: '0700'
      loop: "{{ setup_gather_folders }}"

