---
- name: Gather Resources
  block:
    - name: Gather files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0700"
      loop: "{{ setup_gather_files }}"
      no_log: true

    - name: Gather directory
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "0700"
      loop: "{{ setup_gather_folders }}"

