---

- name: GNOME Customisation Install
  block:
    - name: Copy wallpaper file
      become: true
      ansible.builtin.copy:
        src: "{{ home_Dir }}/{{ ansible_dir }}/resources/images/ArchLinux_bkg.png"
        dest: /usr/share/backgrounds/ansible-wallpaper.png
        owner: root
        group: root
        mode: "0444"

    # - name: Reset dconf to default
    #   ansible.builtin.command: "dconf reset -f /"
    #   register: return_code
    #   changed_when: true

    - name: Load dconf backup
      ansible.builtin.shell: "dconf load / < {{ home_Dir }}/dconf_dump.conf"
      register: return_code
      changed_when: true

    - name: Create mimeapps.list if it doesn't exist
      become: true
      ansible.builtin.file:
        path: /usr/share/applications/mimeapps.list
        state: touch
        mode: "0444"

    - name: Fix VSCode override by adding Default Applications to mimeapps.list
      become: true
      ansible.builtin.lineinfile:
        path: /usr/share/applications/mimeapps.list
        line: "[Default Applications]\ninode/directory=org.gnome.Nautilus.desktop"
        insertafter: EOF