---
# tasks file for post

- name: Gnome-extensions install
  ansible.builtin.include_tasks: gnome-extensions.yml

- name: GNOME Customisation install
  ansible.builtin.include_tasks: gnome_customisation.yml
