
user_name: "dameon"
home_dir: "/home/{{ user_name }}"
source_dir: "{{ home_dir }}/.local/share/chezmoi"

ansible_dir: "{{ source_dir }}/Development/ansible/arch_config"

my_password: "{{ ansible_dir }}/group_vars/vault_ansible_become_pass.yml"

