---
# tasks file for pre

- name: Obtain become password
  vars_prompt:
    - name: become_pass
      prompt: "Enter the become password"
      private: true # Do not echo the input
      encrypt: "sha256_crypt" # Encrypting the password (optional, for demonstration)
      confirm: true # Ask for confirmation

- name: Store become password securely
  ansible.builtin.copy:
    content: "{{ become_pass }}"
    dest: "{{ base_source_dir }}/Development/ansible/arch_config/roles/pre/vars/become_pass.yml"
    mode: '0600'
  delegate_to: localhost
