- name: Ensure the repositories directory exists
  ansible.builtin.file:
    path: "{{ home_dir }}/tracked_repos"
    state: directory
    mode: '0755'

- name: Ensure individual repository directory exists
  ansible.builtin.file:
    path: "{{ home_dir }}/tracked_repos/{{ icon_item.name }}"
    state: directory
    mode: '0755'

- name: Clone repository if not already present
  ansible.builtin.git:
    repo: "{{ icon_item.url }}"
    dest: "{{ home_dir }}/tracked_repos/{{ icon_item.name }}"
    clone: yes
    update: yes

- name: Find the index.theme file within the cloned directory
  ansible.builtin.find:
    paths: "{{ home_dir }}/tracked_repos/{{ icon_item.name }}"
    patterns: 'index.theme'
    recurse: yes
  register: find_index_theme

- name: Create symbolic link for the theme or icon
  ansible.builtin.file:
    src: "{{ find_index_theme.files[0].path | dirname }}"
    dest: "{{ home_dir }}/.local/share/icons/{{ icon_item.name }}"
    state: link
    force: yes
  when: find_index_theme.matched > 0
