---

- name: Install resources and config files
  block:
    - name: Install ZSH plugins
      become: true
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        depth: "{{ item.depth | default(omit) }}"
      loop: "{{ zsh_addons }}"

    - name: Placing files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0700"
      loop: "{{ files_to_copy }}"

    - name: Placing directory
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0700'
      loop: "{{ folders_to_copy }}"

    - name: Read password from vault file
      set_fact:
        my_password: "{{ lookup('file', '{{ my_password }}') }}"
    - name: Decrypt the archive with Ansible Vault
      ansible.builtin.command:
        cmd: ansible-vault decrypt ""/tmp/dconf_backups.tar.gz""
        stdin_add_newline: yes
        stdin: "{{ my_password }}"
      no_log: true

    - name: Extract the archive to restore the dconf_backup directory
      ansible.builtin.unarchive:
        src: "/tmp/dconf_backups.tar.gz"
        dest: "{{ home_dir }}"
        mode: "0700"
