---
- name: Clone GNOME icons
  block:
    - name: Ensure the repositories directory exists
      ansible.builtin.file:
        path: "{{ home_dir }}/tracked_repos"
        state: directory
        mode: '0755'
    
    - name: Clone GNOME icons
      include_tasks: clone_and_link.yml
      loop: "{{ gnome_icons }}"
      loop_control:
        loop_var: icon_item


  #   - name: Ensure individual repository directory exists
  #     ansible.builtin.file:
  #       path: "{{ home_dir }}/tracked_repos/{{ item.name }}"
  #       state: directory
  #       mode: '0755'
    
  #   - name: Clone repository if not already present
  #     ansible.builtin.git:
  #       repo: "{{ item.url }}"
  #       dest: "{{ home_dir }}/tracked_repos/{{ item.name }}"
  #       clone: yes
  #       update: yes
    
  #   - name: Create symbolic link for the cloned theme or icon
  #     ansible.builtin.file:
  #       src: "{{ home_dir }}/tracked_repos/{{ item.name }}"
  #       dest: "{{ home_dir }}/.local/share/icons/{{ item.name }}"
  #       state: link
  #       force: yes
  # loop: "{{ gnome_icons }}"

      

    # - name: Set GNOME icon theme
    #   ansible.builtin.shell: |
    #     dbus-launch --exit-with-session gsettings set org.gnome.desktop.interface icon-theme 'YourIconTheme'
    #   become_user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
    #   become: false
