---
# vars file for setup

setup_gather_files:
  - src: "/home/dameon/.zprofile"
    dest: "/home/dameon/.local/share/chezmoi/Development/ansible/arch_config/resources/files/.zprofile"

  - src: "/home/dameon/.zsh_history"
    dest: "/home/dameon/.local/share/chezmoi/Development/ansible/arch_config/resources/files/.zsh_history"

  - src: "/home/dameon/.zshrc"
    dest: "/home/dameon/.local/share/chezmoi/Development/ansible/arch_config/resources/files/.zshrc"

  - src: "/home/dameon/.zshrc.zni"
    dest: "/home/dameon/.local/share/chezmoi/Development/ansible/arch_config/resources/files/.zshrc.zni"

  - src: "/home/dameon/.p10k.zsh"
    dest: "/home/dameon/.local/share/chezmoi/Development/ansible/arch_config/resources/files/.p10k.zsh"

  - src: "/home/dameon/.my_aliases"
    dest: "/home/dameon/.local/share/chezmoi/Development/ansible/arch_config/resources/files/.my_aliases"
  
  - src: "/tmp/dconf_backups.tar.gz"
    dest: "/home/dameon/.local/share/chezmoi/Development/ansible/arch_config/resources/files/dconf_backups.tar.gz"

setup_gather_folders:
  - src: "/home/dameon/.config/kitty/"
    dest: "/home/dameon/.local/share/chezmoi/Development/ansible/arch_config/resources/files/kitty/"
  
  # - src: "/home/dameon/dconf_backups"
  #   dest: "/home/dameon/.local/share/chezmoi/Development/ansible/arch_config/resources/files/dconf_backups"

setup_user_name: "dameon"

setup_my_password: "/home/dameon/.local/share/chezmoi/Development/ansible/arch_config/group_vars/vault_ansible_become_pass.yml"
