---
# vars file for setup

setup_gather_files:
  - src: "/home/dameon/.zprofile"
    dest: "/home/dameon/.local/share/chezmoi/Development/ansible/arch_config/resources/files/.zprofile"

  - src: "/home/dameon/.zsh_history"
    dest: "/home/dameon/.local/share/chezmoi/Development/ansible/arch_config/resources/files/.zsh_history"

  - src: "/home/dameon/.zshrc"
    dest: "/home/dameon/.local/share/chezmoi/Development/ansible/arch_config/resources/files/.zshrc"

  - src: "/home/dameon/.zshrc.zni"
    dest: "/home/dameon/.local/share/chezmoi/Development/ansible/arch_config/resources/files/.zshrc.zni"

  - src: "/home/dameon/.p10K.zsh"
    dest: "/home/dameon/.local/share/chezmoi/Development/ansible/arch_config/resources/files/.p10K.zsh"

  - src: "/home/dameon/.my_aliases"
    dest: "/home/dameon/.local/share/chezmoi/Development/ansible/arch_config/resources/files/.my_aliases"

setup_gather_folders:
  - src: "/home/dameon/.config/Kitty/"
    dest: "/home/dameon/.local/share/chezmoi/Development/ansible/arch_config/resources/files/kitty/"
